Lecture 3 hw
Delnote/PythonHW pull request #3
Opened 2022-10-14 12:28 UTC by Delnote

2022-10-14 19:40 UTC, alpakhomov requested changes
2, 3, 4 - все ок (hw4 с помощью itertools.product можно решить в одну строку, но это по желанию)

Поправь плз hw1

2022-10-14 19:40 UTC, alpakhomov commented on Lecture 3/hw/hw1.py
> +    return tp.name
В этом задании:
- если передать список валидаторов в таком порядке [validate_date, validate_line], то в файле с ошибочными строками должно быть 777 строчек; сейчас их 746. Стоит обходить список валидаторов в цикле, а не хардкодить индексы - валидаторов может быть произвольное количество.
- файл result.txt не закрывается в этом решении. Можно открыть сразу несколько файлов в context manager

2022-10-16 09:03 UTC, Delnote commented on Lecture 3/hw/hw1.py
> +    return tp.name
Я проапдейтил проверки без хардкода, еще раз все перепроверил. Попробовал собственный набор тестовых данных. И все равно получается 746..... В чем ошибка?

2022-10-16 12:26 UTC, alpakhomov commented on Lecture 3/hw/hw1.py
> +    return tp.name
Проблема в регулярке в validate_date, например строки вроде "2022-10-161616" сейчас считаются валидными. Можно как один из вариантов изменить регулярку (чтобы проверять матч до конца строки).

2022-10-16 18:28 UTC, Delnote commented on Lecture 3/hw/hw1.py
> +    return tp.name
Готово

2022-10-16 20:43 UTC, alpakhomov approved these changes

2022-10-16 21:12 UTC, merged